---
- name: Web Server removal
  hosts: all

  tasks:

    - name: Ensuring W3Svc is stopped
      ansible.windows.win_service:
        name: W3Svc
        state: stopped

    - name: Ensuring Web-Server feature is removed
      ansible.windows.win_feature:
        name: Web-Server
        state: absent
...
