---
- name: Windows_product_facts from docs.ansible.com
  hosts: all

  tasks:

    - name: Get product id and product key
      register: product_facts
      ansible.windows.win_product_facts:

    - name: Printing product_facts
      ansible.builtin.debug:
        var: product_facts
...
