---
- name: Get Service
  hosts: all

  tasks:

  - name: Getting a list of services on my machine
    register: servicelist
    win_shell:  Get-Service

  - name: Printing service list
    ansible.builtin.debug:
      var: servicelist