---
- name: Get Process
  hosts: all

  tasks:

    - name: Getting a list of processes on my machine
      register: processlist
      ansible.windows.win_shell: Get-Process

    - name: Printing processlist list
      ansible.builtin.debug:
        var: processlist
...
