---
- name: Let everyone know a new demo server is born
  hosts: localhost
  gather_facts: false

  tasks:

   - name: Send an email with the link to the aap demo Server
     community.general.mail:
       host: "{{ smtpserver }}"
       port: "{{ smtp_port }}"
       secure: try
       username: "{{ username }}"
       password: "{{ password }}"
       subject: Ansible Automation Platform (AAP) Daily Demo - Windows
       body: "System {{ my_server }} has been successfully provisioned using AAP. The playbooks and notes can be found here: https://github.com/ericcames/Windows/tree/main/AWS The following address http://{{ my_server }} will take you to a custom website. The server will be destroyed at 01:15 AM UTC time. Remote Desktop is enabled for the devops user and the password is redhat321"
       from: "{{ mailfrom }}"
       to: "{{ mailto }}"
       bcc: "{{ bccto }}"