---
- name: Build our custom website
  hosts: all
  gather_facts: no
  vars:
    iis_sites:
      - name: 'AnsibleDemo'
        port: '80'
        path: 'C:\sites\dailydemo'
    iis_test_message: "Hello World!  My test IIS Server"
    ansible_connection: winrm
    ansible_winrm_transport: credssp
    ansible_winrm_server_cert_validation: ignore
    ansible_port: 5986

  tasks:

    - name: Install IIS Webserver
      ansible.builtin.win_feature:
        name: Web-Server
        state: present
    
    - name: Delete default IIS website
      ansible.builtin.win_iis_website:
        name: "Default Web Site"
        state: absent

    - name: Create site directory structure
      with_items: "{{ iis_sites }}"
      ansible.builtin.win_file:
        path: "{{ item.path }}"
        state: directory

    - name: Create IIS site
      with_items: "{{ iis_sites }}"
      notify: restart iis service
      ansible.builtin.win_iis_website:
        name: "{{ item.name }}"
        state: started
        port: "{{ item.port }}"
        physical_path: "{{ item.path }}"
      
    - name: Open port for site on the firewall
      with_items: "{{ iis_sites }}"
      ansible.builtin.win_firewall_rule:
        name: "iisport{{ item.port }}"
        enable: yes
        state: present
        localport: "{{ item.port }}"
        action: Allow
        direction: In
        protocol: Tcp
      
    - name: Template simple web site to iis_site_path as index.html
      with_items: "{{ iis_sites }}"
      ansible.builtin.win_template:
        src: 'index.html.j2'
        dest: '{{ item.path }}\index.html'

    - name: Copy a single file
      with_items: "{{ iis_sites }}"
      ansible.builtin.win_copy:
        src: images/aap.png
        dest: "{{ item.path }}/aap.png"
      
    - name: Show website addresses
      loop:
        - http://{{ inventory_hostname }}
      ansible.builtin.debug:
        msg: "{{ item }}"
      
  handlers:

    - name: restart iis service
      ansible.builtin.win_service:
        name: W3Svc
        state: restarted
        start_mode: auto