---
- name: Install Specific versions of packages using Chocolatey
  hosts: all
  gather_facts: false
  vars:
    choco_packages:
      - name: nodejs
        version: 13.0.0
      - name: python
        version: 3.6.0

  tasks:

    - name: Install specific versions of packages sequentially
      loop: "{{ choco_packages }}"
      chocolatey.chocolatey.win_chocolatey:
        name: "{{ item.name }}"
        version: "{{ item.version }}"
        state: present

    - name: Check python version
      register: check_python_version
      ansible.windows.win_command: python --version

    - name: Check nodejs version
      register: check_node_version
      ansible.windows.win_command: node --version

    - name: Print the version of the software installed
      ansible.builtin.debug:
        msg: Python Version is {{ check_python_version.stdout_lines[0] }} and NodeJS version is {{ check_node_version.stdout_lines[0] }}
...
