---
- name: Update all packages using Chocolatey
  hosts: all
  gather_facts: false
  tasks:

    - name: Update all installed packages
      chocolatey.chocolatey.win_chocolatey:
        name: all
        state: latest

    - name: Check python version
      register: check_python_version
      ansible.windows.win_command: python --version

    - name: Check nodejs version
      register: check_node_version
      ansible.windows.win_command: node --version

    - name: Printing the version of software updated
      ansible.builtin.debug:
        msg: Python Version is {{ check_python_version.stdout_lines[0] }} and NodeJS version is {{ check_node_version.stdout_lines[0] }}
...
